# Generated by Django 5.1.1 on 2024-09-08 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='duration',
            new_name='break_duration',
        ),
        migrations.AddField(
            model_name='session',
            name='study_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
