# Generated by Django 5.1.1 on 2024-09-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_duration_session_break_duration_and_more'),
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
    ]
